### ISSUE TITLE
dem_coreg.py fails: wrong shape for reference and to be aligned DEM

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/DemUtils#7]
Running 'python DemUtils/coreg.py' fails with error:
>  File "DemUtils/coreg.py", line 196, in icp_coregistration
>   assert reference_dem.shape == dem_to_be_aligned.shape
> AssertionError

This is because of several issues. Be aware that rasterio ds shapes will be (nbands, height, width), so even for single band raster, shape will be of length 3. Hence the following issues:
- https://github.com/GlacioHack/DemUtils/blob/95cf00be26499b09830e300f273d25ceef4a3b57/DemUtils/coreg.py#L630 
shape[1] should be shape[2]
- https://github.com/GlacioHack/DemUtils/blob/95cf00be26499b09830e300f273d25ceef4a3b57/DemUtils/coreg.py#L197
 a shape of length 3 is compared with a shape of length 2

Also, at https://github.com/GlacioHack/DemUtils/blob/95cf00be26499b09830e300f273d25ceef4a3b57/DemUtils/coreg.py#L629 (and after), I would suggest to:
- use rasterio's format for bounding box: https://rasterio.readthedocs.io/en/latest/api/rasterio.coords.html?highlight=bounding%20box#rasterio.coords.BoundingBox
- use georaster reproject method: https://github.com/GlacioHack/GeoUtils/blob/6874974de061613786dff0679f7c2769c7236a08/geoutils/georaster.py#L339

**Comment by adehecq** [comment]
Related shape issue at line https://github.com/GlacioHack/DemUtils/blob/95cf00be26499b09830e300f273d25ceef4a3b57/DemUtils/coreg.py#L207

**Comment by adehecq** [comment]
Here is a quick fix, but I believe the issue should be analyzed more in depth:
```
diff --git a/DemUtils/coreg.py b/DemUtils/coreg.py
index acb58ea..8a18852 100644
--- a/DemUtils/coreg.py
+++ b/DemUtils/coreg.py
@@ -626,7 +626,7 @@ class Coregistration:
 
         intersection = reference_raster.intersection(to_be_aligned_raster)
         bounds = dict(zip(["west", "south", "east", "north"], intersection))
-        resolution = (bounds["east"] - bounds["west"]) / reference_raster.data.shape[1]
+        resolution = (bounds["east"] - bounds["west"]) / reference_raster.data.shape[2]
 
         # TODO: Read the to_be_aligned_dem from the actual to_be_aligned_raster and not its filename
         # TODO: The above leads to highly surprising results sometimes if the raster had been modified from its file.
@@ -639,7 +639,7 @@ class Coregistration:
 
         # Align the raster using the selected method. This returns a numpy array and the corresponding error
         aligned_dem, error = self.method(  # type: ignore
-            reference_dem=reference_raster.data,
+            reference_dem=reference_raster.data.squeeze(),
             dem_to_be_aligned=to_be_aligned_dem,
             bounds=bounds,
             crs=reference_raster.crs

```

**Comment by eriksholmlund** [comment]
All suggestions have been taken into account for as of commit 36dbf5bae0f576cdde2e6c3ded82b57d54c69ec9
